/**** TP2 *******/ 
/***** Création des tables du cas CIPRÉ ******/

create table MEMBRE (
  NO_MEMBRE, 
  UTILISATEUR_MEM, 
  MOT_DE_PASSE_MEM, 
  NOM_MEM, 
  PRENOM_MEM,
  ADRESSE_MEM, 
  CODE_POSTAL_MEM, 
  PAYS_MEM, TEL_MEM, 
  FAX_MEM,
  LANGUE_CORRESPONDANCE_MEM, 
  NOM_FICHIER_PHOTO_MEM, 
  ADRESSE_WEB_MEM,
  INSTITUTION_MEM, 
  COURRIEL_MEM, 
  EST_ADMINISTRATEUR_MEM, 
  EST_SUPERVISEUR_MEM,
  EST_APPOUVEE_INSCRIPTION_MEM, NO_MEMBRE_PATRON#
                    
 );


PROJET (NO_PROJET, NOM_PRO, MNT_ALLOUE_PRO, STATUT_PRO, DATE_DEBUT_PRO, DATE_FIN_PRO)
EQUIPE_PROJET (NO_MEMBRE# NO_PROJET#, EST_DIRECTEUR_PRO)
NOTIFICATION (NO_NOTIFICATION, NOM_NOT, DATE_ECHEANCE_NOT, ETAT_NOT, NOTE_NOT,
NO_MEM_ADMIN_CREATION#, NO_MEM_ATTRIBUTION#)
RAPPORT (NO_RAPPORT, NO_PROJET#, TITRE_RAP, NOM_FICHIER_RAP, DATE_DEPOT_RAP,
CODE_ETAT_RAP#)
RAPPORT_ETAT (CODE_ETAT_RAP, NOM_ETAT_RAP)
INSCRIPTION_CONFERENCE (SIGLE_CONFERENCE#, NO_MEMBRE#, DATE_DEMANDE_INS,
STATUT_APPROBATION_INS)
CONFERENCE (SIGLE_CONFERENCE, TITRE_CON, DATE_DEBUT_CON, DATE_FIN_CON, LIEU_CON,
ADRESSE_CON)
