/**** TP2 *******/ 
/***** Création des tables du cas CIPRÉ ******/

create table MEMBRE (
  NO_MEMBRE, 
  UTILISATEUR_MEM, 
  MOT_DE_PASSE_MEM, 
  NOM_MEM, 
  PRENOM_MEM,
  ADRESSE_MEM, 
  CODE_POSTAL_MEM, 
  PAYS_MEM, TEL_MEM, 
  FAX_MEM,
  LANGUE_CORRESPONDANCE_MEM, 
  NOM_FICHIER_PHOTO_MEM, 
  ADRESSE_WEB_MEM,
INSTITUTION_MEM, COURRIEL_MEM, EST_ADMINISTRATEUR_MEM, EST_SUPERVISEUR_MEM,
EST_APPOUVEE_INSCRIPTION_MEM, NO_MEMBRE_PATRON#
                    
 );
